### ISSUE TITLE
What is bash hs?

### ISSUE THREAD

**Issue by klarkc** [cgohla/pureshell#1]
I was trying to build the source code and found this:

```
/home/bgohla/src/vendor/bash/hs/*.cabal
```

in the cabal file, that is failing in `cabal build`, what is that?

**Comment by cgohla** [comment]
Thanks for your question @klarkc 

That's a local fork of the [bash](https://hackage.haskell.org/package/bash) package. I will make it available on GH ASAP, and update the project file here. Sorry about that.

**Comment by klarkc** [comment]
no problem, thanks!

**Comment by cgohla** [comment]
This commit should fix it. Let me know if you're still having trouble.

https://github.com/cgohla/pureshell/commit/2f97b03664ddcfddf7de0deeb0f1ee6b442cce05
